./" System Dog
./" A system information fetcher.
./"
./" Copyright (c) 2022 Azrael JD.
./"
./" This documentation is freely usable and distributable
./" under the terms of the Azratek Documentation License.
./"
./" Disclaimer:
./" THIS DOCUMENTATION IS PROVIDED "AS IS" WITHOUT ANY WARRANTY. IN NO EVENT
./" SHALL THE AUTHORS, CONTRIBUTORS, NOR THE COPYRIGHT HOLDERS BE LIABLE FOR
./" ANY DAMAGE CAUSED BY THE USE OF THIS DOCUMENTATION.

.TH SYSTEMDOG 1 "January 2022" "System Dog 0.1"
.SH NAME
System Dog - A system information fetcher.
.SH SYNOPSIS
systemdog [options]
.SH OPTIONS
-h, --help
.TP
Print this text and exit.
.TP
-v, --version
.TP
Print System Dog version.
